### ISSUE TITLE
"Re+Posts" Feed (maybe just cosmetical)

### ISSUE THREAD

**Issue by kw-666** [skyfeed-dev/feed-generator#4]
not sure if this is the right place for a feature request. At the moment the "Re+Posts" Custum Feed works well - but it is not recognizable which of my followees are reposting it. Its just the post from original poster in timeline which sometimes feels strange because one onders where this repost is coming from.
In "regular" timeline there is a "repostet by XY" notice above. Would be great if this can also be included in the reposts generated by this custom feed.

**Comment by redsolver** [comment]
Hi, this should be fixed now!

**Comment by kw-666** [comment]
Great thanks it works!
